#!/usr/bin/env python

import os, sys
# Set project dir. (.. from this file)
PROJECT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
# Insert project dir to $PATH.
sys.path.insert(0, PROJECT_DIR)

# Import app factory.
from barscreen.app import create_app

# Initilize local app in debug mode.
app = create_app()
app.run("127.0.0.1", port=5000, debug=True)
