#!/usr/bin/env python

"""
Migration script config.

To add a new migration
"""

from alembic.config import main
import sys
from os.path import abspath, dirname
sys.path.insert(0, abspath(dirname(dirname(__file__))))

main()