#!/usr/bin/env python

# Add the base project directory to $PATH.
import os
import sys

# Set project dir. (.. from this file)
PROJECT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
# Insert project dir to $PATH.
sys.path.insert(0, PROJECT_DIR)

# Load env variables.
from barscreen.utils import read_env
read_env(".env")

# Create the flask application.
import logging
from barscreen.app import create_app
shell_app = create_app()

# Imports to have available in shell.
from IPython import start_ipython
from barscreen.database import *

# Initialize ipython shell with all locals imported.
with shell_app.app_context():
    start_ipython(argv=["--no-banner"], user_ns=locals())
